language: go
go:
  - "1.10.x"

sudo: required
services:
  - docker

script:
  - docker run -d --rm -p "36363:5432" -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=fhirbase postgres:10.4
  - bash -c 'while ! nc -z localhost 36363 ; do sleep 1 ; done'
  - make
  - PGUSER=postgres PGPASSWORD=postgres PGDATABASE=fhirbase PGPORT=36363 make test

before_install:
  - curl https://glide.sh/get | sh
