sudo: required
services:
  - docker

script:
  - docker run --rm -p "36363:5432" -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=fhirbase postgres:10.4
  - sleep 3
  - make
  - PGUSER=postgres PGPASSWORD=postgres PGDATABASE=fhirbase PGPORT=36363 make test

before_install:
  - echo "before install"
