FROM golang:1.14-buster as build

WORKDIR $GOPATH/src/github.com/3778/fhirbase/

COPY . .

RUN make

RUN cp ./bin/fhirbase /go/bin/fhirbase

FROM debian:stable-slim as dist

RUN apt-get -qqy update \
 && apt-get -qqy dist-upgrade \
 && apt-get -qqy install \
    ca-certificates \
 && apt-get -qqy autoremove \
 && apt-get -qqy clean \
 && rm -rf /var/lib/apt/*

COPY --from=build /go/bin/fhirbase /usr/local/bin/fhirbase

CMD ["/usr/local/bin/fhirbase"]
