[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.13.3"

[[constraint]]
  name = "github.com/jackc/pgx"
  version = "3.2.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "934abfb2f102315b5794e15ebc7949e4ca253920"

[prune]
  unused-packages = true

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/vbauerster/mpb"
  version = "3.3.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"
