apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fbdemo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      environment: master
      service: fbdemo
      system: fbdemo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        environment: master
        service: fbdemo
        system: fbdemo
    spec:
      containers:
      - image: eu.gcr.io/aidbox2-205511/fhirbase-demo:1
        imagePullPolicy: Always
        name: fbdemo
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
