apiVersion: v1
kind: Service
metadata:
  labels:
    environment: master
    service: fbdemo
    system: fbdemo
  name: fbdemo
  namespace: default
spec:
  ports:
  - name: usnpi
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    environment: master
    service: fbdemo
  sessionAffinity: None
  type: ClusterIP
